name: NodeJS with Grunt

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        git clone https://github.com/phetsims/assert.git
        git clone https://github.com/phetsims/axon.git
        git clone https://github.com/phetsims/babel.git
        git clone https://github.com/phetsims/brand.git
        git clone https://github.com/phetsims/charges-and-fields.git
        git clone https://github.com/phetsims/chipper.git
        git clone https://github.com/phetsims/dot.git
        git clone https://github.com/phetsims/joist.git
        git clone https://github.com/phetsims/kite.git
        git clone https://github.com/phetsims/perennial.git perennial-alias
        git clone https://github.com/phetsims/phet-core.git
        git clone https://github.com/phetsims/phetcommon.git
        git clone https://github.com/phetsims/phetmarks.git
        git clone https://github.com/phetsims/query-string-machine.git
        git clone https://github.com/phetsims/scenery.git
        git clone https://github.com/phetsims/scenery-phet.git
        git clone https://github.com/phetsims/sherpa.git
        git clone https://github.com/phetsims/sun.git
        git clone https://github.com/phetsims/tambo.git
        git clone https://github.com/phetsims/tandem.git
        git clone https://github.com/phetsims/twixt.git
        git clone https://github.com/phetsims/utterance-queue.git
        grunt --brands=adapted-from-phet
